@startuml
class Human {
    - int age
    - String name
    + void drive(Car car)
}

class Car {
    - String brand
    - Engine engine
    + void run()
    + String get_engine_model()
}

class Engine {
    - String model
    - int max_speed
    + String get_model()
}

Engine o-up-> Car

Human .right.> Car

@enduml