@startuml 组合
class Face {
    - Eye eye
    - Nose node
    - Ear ear
    - Mouth mouth
    + void smile(int level)
    + void cry(int level)
}

class Mouth {
    - int[] natural_shape
    - int[] smile_shape
    - int[] cry_shape
    + void smile(int level)
    + void cry(int level)
}

Mouth *-right-> Face
@enduml